# Generated by Django 5.1.7 on 2025-04-07 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0005_tarefa_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentorado',
            new_name='Mentorados',
        ),
    ]
