# Generated by Django 5.1.7 on 2025-04-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0006_rename_mentorado_mentorados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefa',
            new_name='Tarefas',
        ),
    ]
