# Generated by Django 5.1.7 on 2025-04-07 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0007_rename_tarefa_tarefas'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
